# Generated by Django 5.2.15 on 2026-07-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0011_remove_category_remarks_asset_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('attachment_type', models.CharField(choices=[('PHOTO', 'Photo'), ('INVOICE', 'Invoice'), ('WARRANTY', 'Warranty'), ('MANUAL', 'Manual'), ('SERVICE', 'Service'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assets.asset')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
