# Generated by Django 5.2.15 on 2026-07-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
