# Generated by Django 5.2.15 on 2026-07-05 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_purchase_date_asset_purchase_price_and_more'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='suppliers.supplier'),
            preserve_default=False,
        ),
    ]
