# Generated by Django 5.2.15 on 2026-07-05 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_supplier'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='departments.department'),
            preserve_default=False,
        ),
    ]
