# Generated by Django 5.2.15 on 2026-07-05 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_asset_location'),
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='manufacturers.manufacturer'),
            preserve_default=False,
        ),
    ]
