# Generated by Django 5.2.15 on 2026-07-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_category_remarks_alter_asset_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='remarks',
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
