# Generated by Django 5.2.15 on 2026-07-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_remove_category_remarks_asset_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/'),
        ),
    ]
