# Generated by Django 5.2.15 on 2026-07-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_asset_asset_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
        migrations.AddField(
            model_name='asset',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='assets/qrcodes/'),
        ),
    ]
